package com.ascend.lifeos.data.training.packs

import com.ascend.lifeos.data.training.ExerciseEdgeEntity
import com.ascend.lifeos.data.training.ExerciseEntity

/**
 * Aggregator for the generated ExerciseDB v2 packs (plan U02 §2.7).
 *
 * REGENERATED by tools/exercisedb/codegen.js — do not hand-edit the generated
 * pack files; this aggregator keeps a stable API for the seed:
 *  - [upgrade] lifts an existing seed entry onto its researched v2 attributes
 *    (shares, pattern, equipment, difficulty, cues, …) — identity when no
 *    override exists (the honest unknown state).
 *  - [NEW] are exercises that only exist in packs (feeders, variants, KB, …).
 *  - [EDGES] is the full progression-graph edge set.
 *  - [CATALOG_HASH] changes iff any pack content changes; the seeding call
 *    upserts only when the hash moved (cold-start guard, §2.4.3).
 */
object ExercisePacks {

    val NEW: List<ExerciseEntity> get() = emptyList()

    val EDGES: List<ExerciseEdgeEntity> get() = emptyList()

    const val CATALOG_HASH: String = "v2-scaffold-0"

    fun upgrade(e: ExerciseEntity): ExerciseEntity = e
}
